version: "3.8"
services:
  backend:
    image: "btk25301/springboot-react-fullstack:28.2.2022.2.56.10"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev