version: "3.8"
services:
  backend:
    image: "btk25301/springboot-react-fullstack:3.3.2022.4.42.50"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev